turyan_retail:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: analytics_dev
      host: host.docker.internal
      port: 18123
      user: admin
      password: "xT2vBGuvLMy8MJKzu2PD"
      secure: false

    prod:
      type: clickhouse
      schema: analytics
      host: "{{ env_var('CH_HOST', 'clickhouse') }}"
      port: "{{ env_var('CH_PORT', '8123') | int }}"
      user: "{{ env_var('CH_USER', 'default') }}"
      password: "{{ env_var('CH_PASSWORD', '') }}"
      secure: false