name: CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]


jobs:
    validate:
        runs-on: self-hosted
        
        steps:
          - uses: actions/checkout@v4


          - name: Set up virtualenv
            run: |
                sudo apt-get update -y
                sudo apt install python3-venv -y
                python3 -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements-ci.txt

          - name: Lint
            run: | 
                . .venv/bin/activate
                ruff check dags/
          - name: DAG import test
            run: |
                . .venv/bin/activate
                python tests/dag_import_test.py
                

